### ISSUE TITLE
JIRA reader metrics looks incomplete

### ISSUE THREAD

**Issue by mhow2** [crossminer/scava#169]
So now it seems we're able to have some data retrieve from JIRA, but it looks incomplete (or wrong).

The task ran as [in this JSON snippet](https://privatebin.ow2.org/?e1abd0373c293f26#gn2qx4i39bbetEMEDvnvKWMQcvtJqP+ZEzEZRhwipio=) ( analysis from 2019-03-01 to 2019-04-11).
I selected 48 metrics from the Admin UI, filtering on "bugs".

Resulting metrics as CSV : [xwiki-metrics-values.csv.gz](https://github.com/crossminer/scava/files/3068575/xwiki-metrics-values.csv.gz)
It misses the "emotions" metrics and some values looks inconsistent,  for ex `bugs.averageResponseTime` is always zero

@creat89 are you able to reproduce on your side ? The project is again https://github.com/xwiki/xwiki-platform and for JIRA you either still have my credentials OR you'd have to create an account.

Regards.

**Comment by creat89** [comment]
I cannot reproduce the issue. Here is one of the things I can retrieve:
```
/* 42 */
{
    "_id" : "7a47045d-1713-442e-967a-34582cce89db",
    "_type" : "org.eclipse.scava.metricprovider.historic.bugs.severitysentiment.model.BugsSeveritySentimentHistoricMetric",
    "severityLevels" : [ 
        {
            "_id" : "1b25fc6d-f62b-4efb-a278-bce111aca311",
            "_type" : "org.eclipse.scava.metricprovider.historic.bugs.severitysentiment.model.SeverityLevel",
            "severityLevel" : "normal",
            "numberOfBugs" : 111,
            "averageSentiment" : -0.0606249086558819,
            "sentimentAtThreadBeggining" : -0.0990990996360779,
            "sentimentAtThreadEnd" : -0.0270270276814699
        }, 
        {
            "_id" : "24faebfa-d1c3-431d-9462-8765cc720bdf",
            "_type" : "org.eclipse.scava.metricprovider.historic.bugs.severitysentiment.model.SeverityLevel",
            "severityLevel" : "unknown",
            "numberOfBugs" : 124,
            "averageSentiment" : 0.0,
            "sentimentAtThreadBeggining" : 0.0,
            "sentimentAtThreadEnd" : 0.0
        }
    ],
    "__date" : "20190411",
    "__datetime" : ISODate("2019-04-10T23:00:00.000Z")
}
```
 The 124 bugs with unknown severity means that they didn't contain any message. Thus, it was impossible to calculate the severity or the sentiments. While for 111 bugs, there was at least one message and we determined that the severity was normal, and the sentiment could be considered as neutral but with a negative tendency. 

 I guess this is still related, somehow, to at least one classifier not being loaded correctly. I'll try to install the docker image of the platform on our server.  And check whether I can reproduce the error. In the mean time, can you tell me if you are using the build created  on the 10th April (which contains a patch for the models not being loaded)? If so, can you check in the log if there is any error telling `Error while loading the model:` followed by a stack trace?

**Comment by creat89** [comment]
Just as an extra information, this is what I get form the historic emotion metric:
```
/* 42 */
{
    "_id" : "7dc06a2e-c2bf-4d38-b770-6d66117284b3",
    "_type" : "org.eclipse.scava.metricprovider.historic.bugs.emotions.model.BugsEmotionsHistoricMetric",
    "bugData" : [ 
        {
            "_id" : "8072eacc-a75f-41f0-89f1-cb772b8b26cc",
            "_type" : "org.eclipse.scava.metricprovider.historic.bugs.emotions.model.BugData",
            "bugTrackerId" : "https://jira.xwiki.org:XWIKI:jira",
            "cumulativeNumberOfComments" : 331,
            "numberOfComments" : 21
        }
    ],
    "dimensions" : [ 
        {
            "_id" : "6827fd4e-6ce1-4793-8404-b06d5f7423a6",
            "_type" : "org.eclipse.scava.metricprovider.historic.bugs.emotions.model.Dimension",
            "bugTrackerId" : "https://jira.xwiki.org:XWIKI:jira",
            "emotionLabel" : "__label__sadness",
            "cumulativeNumberOfComments" : 65,
            "cumulativePercentage" : 19.6374626159668,
            "numberOfComments" : 13,
            "percentage" : 61.9047622680664
        }, 
        {
            "_id" : "b6c1cc2e-c2cb-49ee-85ff-f92d26cacca8",
            "_type" : "org.eclipse.scava.metricprovider.historic.bugs.emotions.model.Dimension",
            "bugTrackerId" : "https://jira.xwiki.org:XWIKI:jira",
            "emotionLabel" : "__label__anger",
            "cumulativeNumberOfComments" : 87,
            "cumulativePercentage" : 26.2839870452881,
            "numberOfComments" : 7,
            "percentage" : 33.3333320617676
        }, 
        {
            "_id" : "7072825a-0ff7-446a-be63-c9f8f457be62",
            "_type" : "org.eclipse.scava.metricprovider.historic.bugs.emotions.model.Dimension",
            "bugTrackerId" : "https://jira.xwiki.org:XWIKI:jira",
            "emotionLabel" : "__label__joy",
            "cumulativeNumberOfComments" : 18,
            "cumulativePercentage" : 5.43806648254395,
            "numberOfComments" : 0,
            "percentage" : 0.0
        }, 
        {
            "_id" : "00623081-9459-4793-a23e-e8a6811e02d5",
            "_type" : "org.eclipse.scava.metricprovider.historic.bugs.emotions.model.Dimension",
            "bugTrackerId" : "https://jira.xwiki.org:XWIKI:jira",
            "emotionLabel" : "__label__love",
            "cumulativeNumberOfComments" : 50,
            "cumulativePercentage" : 15.1057405471802,
            "numberOfComments" : 3,
            "percentage" : 14.2857141494751
        }, 
        {
            "_id" : "61917e48-2a99-4dc2-aa44-1232dca56497",
            "_type" : "org.eclipse.scava.metricprovider.historic.bugs.emotions.model.Dimension",
            "bugTrackerId" : "https://jira.xwiki.org:XWIKI:jira",
            "emotionLabel" : "__label__surprise",
            "cumulativeNumberOfComments" : 5,
            "cumulativePercentage" : 1.51057398319244,
            "numberOfComments" : 0,
            "percentage" : 0.0
        }, 
        {
            "_id" : "34534896-4b12-4ad8-9f44-6aed1c9372e3",
            "_type" : "org.eclipse.scava.metricprovider.historic.bugs.emotions.model.Dimension",
            "bugTrackerId" : "https://jira.xwiki.org:XWIKI:jira",
            "emotionLabel" : "__label__fear",
            "cumulativeNumberOfComments" : 3,
            "cumulativePercentage" : 0.906344413757324,
            "numberOfComments" : 0,
            "percentage" : 0.0
        }
    ],
    "__date" : "20190411",
    "__datetime" : ISODate("2019-04-10T23:00:00.000Z")
}
```

**Comment by mhow2** [comment]
> if you are using the build created on the 10th April (which contains a patch for the models not being loaded)?
Yes it was

I did another try with today's build (Apr 12 : http://ci5.castalia.camp:8080/job/scava-metric-platform/job/dev/148 ). I still observe the same behavior when looking at the metrics results.

Here are the logs, one is the container output itself, and the later the log which is set up by prop.properties file in oss-app) : 

[scava-deployment_oss-app_1-2019-04-12@08:53.log](https://github.com/crossminer/scava/files/3072443/scava-deployment_oss-app_1-2019-04-12%4008.53.log)
[metric-pf.log](https://github.com/crossminer/scava/files/3072444/metric-pf.log)

**Comment by creat89** [comment]
Commit https://github.com/crossminer/scava/commit/cd9dc0c3641f01e2b8fbe1fdd42f78cf0cb29925 should fix the issue and some others that are related.

**Comment by mhow2** [comment]
Hi @creat89 , there is some improvements. But I still don't get `emotions` metrics. Attaching the new log files here:
[metric-pf.log](https://github.com/crossminer/scava/files/3079558/metric-pf.log)
[scava-deployment_oss-app_1-2019-04-15@09:49.log](https://github.com/crossminer/scava/files/3079559/scava-deployment_oss-app_1-2019-04-15%4009.49.log)
[xwiki-metrics-values.csv.gz](https://github.com/crossminer/scava/files/3079561/xwiki-metrics-values.csv.gz)

**Comment by mhow2** [comment]
I see only 47 metrics ticked in the task. It is likely that I have missed some of the checkbox in the admin UI. I'll check once again to confirm.

**Comment by mhow2** [comment]
I've been able to get `bugs.emotions` metrics. I restarted from scratch per my previous comment. In the task definition, I chose metrics with filter "**bug**". eg. not **bugs** because if you do that not all the required metrics gets displayed available to select. Total are 50 metrics selected.

**Comment by creat89** [comment]
So, now that you can get the metrics correctly, can we close this issue?

**Comment by mhow2** [comment]
OK. I will reopen if I see anything else missing in the metrics. Thanks !
