### ISSUE TITLE
Time Out when "Search updates for libraries"

### ISSUE THREAD

**Issue by phkrief** [crossminer/scava#434]
Unfortunately, I cannot test this feature because of this time out.
Thx for your help

io.swagger.client.ApiException: java.net.SocketTimeoutException: timeout
	at io.swagger.client.ApiClient.execute(ApiClient.java:842)
	at io.swagger.client.api.RecommenderRestControllerApi.getVersionsUsingPOSTWithHttpInfo(RecommenderRestControllerApi.java:1559)
	at io.swagger.client.api.RecommenderRestControllerApi.getVersionsUsingPOST(RecommenderRestControllerApi.java:1545)
	at org.eclipse.scava.plugin.libraryversions.LibraryVersionModel.getAvailableVersionsOfLibraries(LibraryVersionModel.java:87)
	at org.eclipse.scava.plugin.libraryversions.checker.LibraryVersionCheckController.lambda$0(LibraryVersionCheckController.java:56)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.SocketTimeoutException: timeout
	at okio.Okio$3.newTimeoutException(Okio.java:207)
	at okio.AsyncTimeout.exit(AsyncTimeout.java:261)
	at okio.AsyncTimeout$2.read(AsyncTimeout.java:215)
	at okio.RealBufferedSource.indexOf(RealBufferedSource.java:306)
	at okio.RealBufferedSource.indexOf(RealBufferedSource.java:300)
	at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:196)
	at com.squareup.okhttp.internal.http.Http1xStream.readResponse(Http1xStream.java:186)
	at com.squareup.okhttp.internal.http.Http1xStream.readResponseHeaders(Http1xStream.java:127)
	at com.squareup.okhttp.internal.http.HttpEngine.readNetworkResponse(HttpEngine.java:737)
	at com.squareup.okhttp.internal.http.HttpEngine.access$200(HttpEngine.java:87)
	at com.squareup.okhttp.internal.http.HttpEngine$NetworkInterceptorChain.proceed(HttpEngine.java:722)
	at com.squareup.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:576)
	at com.squareup.okhttp.Call.getResponse(Call.java:287)
	at com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Call.java:243)
	at com.squareup.okhttp.Call.getResponseWithInterceptorChain(Call.java:205)
	at com.squareup.okhttp.Call.execute(Call.java:80)
	at io.swagger.client.ApiClient.execute(ApiClient.java:838)
	... 5 more
Caused by: java.net.SocketTimeoutException: Read timed out
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
	at java.net.SocketInputStream.read(SocketInputStream.java:171)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at okio.Okio$2.read(Okio.java:139)
	at okio.AsyncTimeout$2.read(AsyncTimeout.java:211)
	... 19 more

**Comment by phkrief** [comment]
FYI, I don't have this issue with the OW2 instance http://scava-dev.ow2.org 
FYI @blueoly

**Comment by geryxyz** [comment]
Could you please specify the exact steps you done? Sample project, server and any other settings you changed?

**Comment by phkrief** [comment]
I have attached the exported project.
Steps:
- Selected the project
- In the context menu, select the item CROSSMINER > Search updates for libraries

Btw, I have the same time out issue with the other menu item CROSSMINER > Search libraries for this project.
Thanks

[jackson-core-example.zip](https://github.com/crossminer/scava/files/3884145/jackson-core-example.zip)

**Comment by geryxyz** [comment]
Okay, which server do you use?

**Comment by phkrief** [comment]
Hi Gergo,

The issue happens with the following instance: http://83.212.75.210

**Comment by phkrief** [comment]
Dear @geryxyz 
Any update on this issue?
Thanks a lot

**Comment by geryxyz** [comment]
Since the server is not maintained by us so we can neither update nor fix it.
We also experienced this issue some times but it should be fixed on the server.
Moreover, it seems to disappear and reappear at random.

**Comment by idarav** [comment]
Dear @phkrief 
The latest version ( 1.21.0.rev0 ) has a new Preference page (Request timeouts) where you can adjust the timeout values for your needs

**Comment by phkrief** [comment]
I just tested against the new version (1.21.0.rev0) I still get an error:
![image](https://user-images.githubusercontent.com/6196602/70388866-f2b6d780-19b7-11ea-8e7f-37b36bfc5ede.png)

The message is:
Swagger client exception details:
Error code: 500
Response headers:
 Content-Type
  application/json;charset=UTF-8
 Transfer-Encoding
  chunked
 Date
  Sun, 08 Dec 2019 11:40:15 GMT
 Connection
  close
 OkHttp-Sent-Millis
  1575805185801
 OkHttp-Received-Millis
  1575805215926
Response body:
{
  "timestamp": 1575805215871,
  "status": 500,
  "error": "Internal Server Error",
  "exception": "org.springframework.dao.DataAccessResourceFailureException",
  "message": "Timed out after 30000 ms while waiting for a server that matches ReadPreferenceServerSelector{readPreference\u003dprimary}. Client view of cluster state is {type\u003dSTANDALONE, servers\u003d[{address\u003dkb-db:27017, type\u003dUNKNOWN, state\u003dCONNECTING, exception\u003d{com.mongodb.MongoSocketOpenException: Exception opening socket}, caused by {java.net.ConnectException: Connection refused (Connection refused)}}]; nested exception is com.mongodb.MongoTimeoutException: Timed out after 30000 ms while waiting for a server that matches ReadPreferenceServerSelector{readPreference\u003dprimary}. Client view of cluster state is {type\u003dSTANDALONE, servers\u003d[{address\u003dkb-db:27017, type\u003dUNKNOWN, state\u003dCONNECTING, exception\u003d{com.mongodb.MongoSocketOpenException: Exception opening socket}, caused by {java.net.ConnectException: Connection refused (Connection refused)}}]",
  "path": "/api/recommendation/version/"
}

and the log:


io.swagger.client.ApiException: 
	at io.swagger.client.ApiClient.handleResponse(ApiClient.java:923)
	at io.swagger.client.ApiClient.execute(ApiClient.java:839)
	at io.swagger.client.api.RecommenderRestControllerApi.getVersionsUsingPOSTWithHttpInfo(RecommenderRestControllerApi.java:1795)
	at io.swagger.client.api.RecommenderRestControllerApi.getVersionsUsingPOST(RecommenderRestControllerApi.java:1781)
	at org.eclipse.scava.plugin.libraryversions.LibraryVersionModel.getAvailableVersionsOfLibraries(LibraryVersionModel.java:85)
	at org.eclipse.scava.plugin.libraryversions.updater.LibraryVersionUpdaterController.init(LibraryVersionUpdaterController.java:59)
	at org.eclipse.scava.plugin.main.page.PageController.onReceiveRoutedEventFromParentController(PageController.java:337)
	at org.eclipse.scava.plugin.mvc.controller.Controller.routeEventToSubControllers(Controller.java:114)
	at org.eclipse.scava.plugin.main.MainController.lambda$0(MainController.java:138)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:185)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4145)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3812)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1160)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1049)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:633)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:557)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:150)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:400)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:660)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:597)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1468)

FYI, I'm running against the Eclipse instance:  http://83.212.75.210

**Comment by phkrief** [comment]
FYI, I tried with the OW2 instance, and the answer is almost immediate. 
I also tried to change the timeout w/o success

**Comment by idarav** [comment]
the part 

> "error": "Internal Server Error",
> "exception": "org.springframework.dao.DataAccessResourceFailureException",
> "message": "Timed out after 30000 ms while waiting for a server that matches ReadPreferenceServerSelector{readPreference\u003dprimary}. Client view of cluster state is {type\u003dSTANDALONE, servers\u003d[{address\u003dkb-db:27017, type\u003dUNKNOWN, state\u003dCONNECTING, exception\u003d{com.mongodb.MongoSocketOpenException: Exception opening socket}, caused by {java.net.ConnectException: Connection refused (Connection refused)}}]; nested exception is com.mongodb.MongoTimeoutException: Timed out after 30000 ms while waiting for a server that matches ReadPreferenceServerSelector{readPreference\u003dprimary}. Client view of cluster state is {type\u003dSTANDALONE, servers\u003d[{address\u003dkb-db:27017, type\u003dUNKNOWN, state\u003dCONNECTING, exception\u003d{com.mongodb.MongoSocketOpenException: Exception opening socket}, caused by {java.net.ConnectException: Connection refused (Connection refused)}}]",

says that something on the server side went wrong, so I think it is a server (knowledge base?) related issue and not a client/plug-in side related anymore. What do you think @md2manoppello  ?

**Comment by phkrief** [comment]
We retrieve the kind of error in #445 : https://github.com/crossminer/scava/issues/445#issuecomment-562676737

**Comment by phkrief** [comment]
I have the impression that the KB crashed again because I cannot even reach the search:

Swagger client exception details:
Error code: 500
Response headers:
 Content-Type
  application/json;charset=UTF-8
 Transfer-Encoding
  chunked
 Date
  Sun, 08 Dec 2019 11:52:02 GMT
 Connection
  close
 OkHttp-Sent-Millis
  1575805891605
 OkHttp-Received-Millis
  1575805922079
Response body:
{
  "timestamp": 1575805922019,
  "status": 500,
  "error": "Internal Server Error",
  "exception": "org.springframework.dao.DataAccessResourceFailureException",
  "message": "Timed out after 30000 ms while waiting for a server that matches ReadPreferenceServerSelector{readPreference\u003dprimary}. Client view of cluster state is {type\u003dSTANDALONE, servers\u003d[{address\u003dkb-db:27017, type\u003dUNKNOWN, state\u003dCONNECTING, exception\u003d{com.mongodb.MongoSocketOpenException: Exception opening socket}, caused by {java.net.ConnectException: Connection refused (Connection refused)}}]; nested exception is com.mongodb.MongoTimeoutException: Timed out after 30000 ms while waiting for a server that matches ReadPreferenceServerSelector{readPreference\u003dprimary}. Client view of cluster state is {type\u003dSTANDALONE, servers\u003d[{address\u003dkb-db:27017, type\u003dUNKNOWN, state\u003dCONNECTING, exception\u003d{com.mongodb.MongoSocketOpenException: Exception opening socket}, caused by {java.net.ConnectException: Connection refused (Connection refused)}}]",
  "path": "/api/artifacts/search/mqtt"
}

**Comment by blueoly** [comment]
The metrics platform container crashed. I restarted it. The KB service was intact.

**Comment by phkrief** [comment]
I couldn't try it before.  Now, the search doesn't work against http://83.212.75.210

**Comment by blueoly** [comment]
@phkrief  Everything is up and running in the instance.

**Comment by phkrief** [comment]
Thx @blueoly
@md2manoppello  I can reach and search against the ow2 instance but I can't against http://83.212.75.210.  Can you double-check, please?
Thanks
