### ISSUE TITLE
Eclipse importer fails to analyse project

### ISSUE THREAD

**Issue by borisbaldassari** [crossminer/scava#82]
When using the eclipse importer for the epsilon project, as proposed in the project creation page itself, errors show up in the logs:

```
oss-app_1         | ERROR [importer.eclipse ] (07:22:00): Problems occurred during the collection of the persons involved in the project modeling.epsilon
oss-app_1         | INFO  [OssmeterApplication] (07:22:01): Worker 'w1' Waiting New Tasks
oss-app_1         | ERROR [importer.eclipse ] (07:22:10): modeling.epsilon importer failed to load NNTP news group url
```

**Comment by borisbaldassari** [comment]
Still happens.. I cannot see the project in the dashboard, but it is marked as "Up To Date" in the admin UI. 
```

2019-02-03T13:52:24.683033323Z INFO  [OssmeterApplication] (13:52:24): Worker 'w1' Executing modeling.epsilon:task1 Task,
2019-02-03T13:52:24.684636217Z INFO  [ProjectExecutor (w1:modeling.epsilon:task1)] (13:52:24): Beginning execution.,
2019-02-03T13:52:24.685498237Z INFO  [ProjectExecutor (w1:modeling.epsilon:task1)] (13:52:24): Creating metric branches.,
2019-02-03T13:52:24.686719879Z INFO  [ProjectExecutor (w1:modeling.epsilon:task1)] (13:52:24): Created metric branches.,
2019-02-03T13:52:24.692948475Z INFO  [ProjectExecutor (w1:modeling.epsilon:task1)] (13:52:24): Dates: 1130,
2019-02-03T13:52:24.693569959Z INFO  [ProjectExecutor (w1:modeling.epsilon:task1)] (13:52:24): Date: 20160101, project: Eclipse Epsilon,
2019-02-03T13:52:24.960962850Z ERROR [ProjectDelta (Eclipse Epsilon,20160101)] (13:52:24): Delta creation failed.,
2019-02-03T13:52:24.960996987Z org.eclipse.jgit.api.errors.InvalidRemoteException: Invalid remote: origin,
2019-02-03T13:52:24.961005625Z 	at org.eclipse.jgit.api.FetchCommand.call(FetchCommand.java:136),
2019-02-03T13:52:24.961012368Z 	at org.eclipse.jgit.api.PullCommand.call(PullCommand.java:248),
2019-02-03T13:52:24.961018554Z 	at org.eclipse.scava.platform.vcs.git.GitManager.getGit(GitManager.java:339),
2019-02-03T13:52:24.961024854Z 	at org.eclipse.scava.platform.vcs.git.GitManager.getRevisionsForDate(GitManager.java:279),
2019-02-03T13:52:24.961031191Z 	at org.eclipse.scava.platform.delta.vcs.PlatformVcsManager.getRevisionsForDate(PlatformVcsManager.java:77),
2019-02-03T13:52:24.961037458Z 	at org.eclipse.scava.platform.delta.vcs.VcsProjectDelta.<init>(VcsProjectDelta.java:25),
2019-02-03T13:52:24.961044528Z 	at org.eclipse.scava.platform.delta.ProjectDelta.create(ProjectDelta.java:60),
2019-02-03T13:52:24.961050740Z 	at org.eclipse.scava.platform.osgi.analysis.ProjectAnalyser.executeAnalyse(ProjectAnalyser.java:102),
2019-02-03T13:52:24.961056999Z 	at org.eclipse.scava.platform.osgi.services.WorkerExecutor.run(WorkerExecutor.java:56),
2019-02-03T13:52:24.961063279Z 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149),
2019-02-03T13:52:24.961069373Z 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624),
2019-02-03T13:52:24.961075411Z 	at java.lang.Thread.run(Thread.java:748),
2019-02-03T13:52:24.961081424Z Caused by: org.eclipse.jgit.errors.NoRemoteRepositoryException: http://git.eclipse.org/c/epsilon/org.eclipse.epsilon.git: http://git.eclipse.org/c/epsilon/org.eclipse.epsilon.git/info/refs?service=git-upload-pack not found,
2019-02-03T13:52:24.961100065Z 	at org.eclipse.jgit.transport.TransportHttp.connect(TransportHttp.java:466),
2019-02-03T13:52:24.961107011Z 	at org.eclipse.jgit.transport.TransportHttp.openFetch(TransportHttp.java:306),
2019-02-03T13:52:24.961113190Z 	at org.eclipse.jgit.transport.FetchProcess.executeImp(FetchProcess.java:136),
2019-02-03T13:52:24.961119337Z 	at org.eclipse.jgit.transport.FetchProcess.execute(FetchProcess.java:122),
2019-02-03T13:52:24.961125325Z 	at org.eclipse.jgit.transport.Transport.fetch(Transport.java:1111),
2019-02-03T13:52:24.961131301Z 	at org.eclipse.jgit.api.FetchCommand.call(FetchCommand.java:130),
2019-02-03T13:52:24.961137715Z 	... 11 more,
2019-02-03T13:52:24.961929828Z ERROR [ProjectExecutor (w1:modeling.epsilon:task1)] (13:52:24): Project delta creation failed. Aborting.,
2019-02-03T13:52:25.354617014Z Feb 03, 2019 1:52:25 PM org.restlet.engine.log.LogFilter afterHandle,
2019-02-03T13:52:25.354628288Z INFO: 2019-02-03	13:52:25	172.21.0.8	-	172.21.0.6	8182	GET	/analysis/workers	-	200	347	0	6	http://oss-app:8182	Mozilla/5.0 (X11; Linux x86_64; rv:60.0) Gecko/20100101 Firefox/60.0	http://ci4.castalia.camp:5601/worker,
```

**Comment by borisbaldassari** [comment]
Still happening as of today. It seems the importer fails to find the correct git repo..
Any progress on this?
``` 
oss-app_1         | ERROR [ProjectDelta (Eclipse Epsilon,20000101)] (06:49:04): Delta creation failed.
oss-app_1         | org.eclipse.jgit.api.errors.InvalidRemoteException: Invalid remote: origin
oss-app_1         |     at org.eclipse.jgit.api.FetchCommand.call(FetchCommand.java:136)
oss-app_1         |     at org.eclipse.jgit.api.PullCommand.call(PullCommand.java:248)
oss-app_1         |     at org.eclipse.scava.platform.vcs.git.GitManager.getGit(GitManager.java:339)
oss-app_1         |     at org.eclipse.scava.platform.vcs.git.GitManager.getRevisionsForDate(GitManager.java:279)
oss-app_1         |     at org.eclipse.scava.platform.delta.vcs.PlatformVcsManager.getRevisionsForDate(PlatformVcsManager.java:77)
oss-app_1         |     at org.eclipse.scava.platform.delta.vcs.VcsProjectDelta.<init>(VcsProjectDelta.java:25)
oss-app_1         |     at org.eclipse.scava.platform.delta.ProjectDelta.create(ProjectDelta.java:61)
oss-app_1         |     at org.eclipse.scava.platform.osgi.analysis.ProjectAnalyser.executeAnalyse(ProjectAnalyser.java:108)
oss-app_1         |     at org.eclipse.scava.platform.osgi.services.WorkerExecutor.run(WorkerExecutor.java:55)
oss-app_1         |     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
oss-app_1         |     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
oss-app_1         |     at java.lang.Thread.run(Thread.java:748)
oss-app_1         | Caused by: org.eclipse.jgit.errors.NoRemoteRepositoryException: http://git.eclipse.org/c/epsilon/org.eclipse.epsilon.git: http://git.eclipse.org/c/epsilon/org.eclipse.epsilon.git/info/refs?service=git-upload-pack not found
oss-app_1         |     at org.eclipse.jgit.transport.TransportHttp.connect(TransportHttp.java:466)
oss-app_1         |     at org.eclipse.jgit.transport.TransportHttp.openFetch(TransportHttp.java:306)
oss-app_1         |     at org.eclipse.jgit.transport.FetchProcess.executeImp(FetchProcess.java:136)
oss-app_1         |     at org.eclipse.jgit.transport.FetchProcess.execute(FetchProcess.java:122)
oss-app_1         |     at org.eclipse.jgit.transport.Transport.fetch(Transport.java:1111)
oss-app_1         |     at org.eclipse.jgit.api.FetchCommand.call(FetchCommand.java:130)
oss-app_1         |     ... 11 more
oss-app_1         | ERROR [ProjectExecutor (w1 : modeling.epsilon:epsilon_task )] (06:49:04): Project delta creation failed. Aborting.
```

**Comment by davidediruscio** [comment]
It seems the git url retrieved by the importer is wrong. In the example, the importer wrongly assigns http://git.eclipse.org/c/epsilon/org.eclipse.epsilon.git instead of git://git.eclipse.org/gitroot/epsilon/org.eclipse.epsilon.git @md2manoppello could you please check?

**Comment by borisbaldassari** [comment]
@davidediruscio  Agreed. Finding the git url for a project can be tricky, but your mechanism usually works well.. It's just bad luck that it's the very example provided in the Project creation page. ;-)
![capture du 2019-02-26 18-54-10](https://user-images.githubusercontent.com/5849071/53434949-f31d4d80-39f7-11e9-858c-45638675eeec.png)

**Comment by md2manoppello** [comment]
It depends on the metadata. I fixed it by a heuristic. Let me know if it works.

**Comment by valeriocos** [comment]
HI @md2manoppello , I guess this issue may be related to https://github.com/crossminer/scava/issues/83#issuecomment-470220226

**Comment by borisbaldassari** [comment]
Still happens as of today: 
```
oss-app_1         | ERROR [ProjectDelta (Eclipse Epsilon,20000101)] (21:38:07): Delta creation failed.
oss-app_1         | org.eclipse.jgit.api.errors.InvalidRemoteException: Invalid remote: origin
oss-app_1         |     at org.eclipse.jgit.api.FetchCommand.call(FetchCommand.java:136)
oss-app_1         |     at org.eclipse.jgit.api.PullCommand.call(PullCommand.java:248)
oss-app_1         |     at org.eclipse.scava.platform.vcs.git.GitManager.getGit(GitManager.java:339)
oss-app_1         |     at org.eclipse.scava.platform.vcs.git.GitManager.getRevisionsForDate(GitManager.java:279)
oss-app_1         |     at org.eclipse.scava.platform.delta.vcs.PlatformVcsManager.getRevisionsForDate(PlatformVcsManager.java:77)
oss-app_1         |     at org.eclipse.scava.platform.delta.vcs.VcsProjectDelta.<init>(VcsProjectDelta.java:25)
oss-app_1         |     at org.eclipse.scava.platform.delta.ProjectDelta.create(ProjectDelta.java:61)
oss-app_1         |     at org.eclipse.scava.platform.osgi.analysis.ProjectAnalyser.executeAnalyse(ProjectAnalyser.java:103)
oss-app_1         |     at org.eclipse.scava.platform.osgi.services.WorkerExecutor.run(WorkerExecutor.java:55)
oss-app_1         |     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
oss-app_1         |     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
oss-app_1         |     at java.lang.Thread.run(Thread.java:748)
oss-app_1         | Caused by: org.eclipse.jgit.errors.NoRemoteRepositoryException: http://git.eclipse.org/c/epsilon/org.eclipse.epsilon.git: http://git.eclipse.org/c/epsilon/org.eclipse.epsilon.git/info/refs?service=git-upload-pack not found
oss-app_1         |     at org.eclipse.jgit.transport.TransportHttp.connect(TransportHttp.java:466)
oss-app_1         |     at org.eclipse.jgit.transport.TransportHttp.openFetch(TransportHttp.java:306)
oss-app_1         |     at org.eclipse.jgit.transport.FetchProcess.executeImp(FetchProcess.java:136)
oss-app_1         |     at org.eclipse.jgit.transport.FetchProcess.execute(FetchProcess.java:122)
oss-app_1         |     at org.eclipse.jgit.transport.Transport.fetch(Transport.java:1111)
oss-app_1         |     at org.eclipse.jgit.api.FetchCommand.call(FetchCommand.java:130)
oss-app_1         |     ... 11 more
oss-app_1         | ERROR [ProjectExecutor (w1:modeling.epsilon:task_epsilon)] (21:38:07): Project delta creation failed. Aborting.
```
Instance was updated this thursday.

**Comment by borisbaldassari** [comment]
Seems to work well now, closing the issue.
